# Generated by Django 5.1.4 on 2025-01-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_clinicpatient_clinic_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedpatient',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
