# Generated by Django 5.1.4 on 2025-01-06 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('medical_history', models.TextField(blank=True, max_length=5000)),
                ('diagnosis', models.TextField(max_length=5000)),
                ('treatment', models.TextField(max_length=5000)),
                ('prescription', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
