# Generated by Django 5.1.4 on 2024-12-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('', 'Select One'), ('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_date', models.DateTimeField()),
                ('department', models.CharField(choices=[('', 'Select One'), ('OPD', 'OPD'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Other', 'Other')], max_length=100)),
                ('reason_for_appointment', models.TextField()),
                ('appointment_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency')], max_length=50)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('referring_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('consent_for_treatment', models.BooleanField(default=False)),
                ('data_privacy_agreement', models.BooleanField(default=False)),
            ],
        ),
    ]
