# Generated by Django 5.1.4 on 2024-12-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0002_remove_appointment_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('', 'Select One'), ('OPD', 'OPD'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('', 'Select One'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
